### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by nmrao** [pmcneil/OneRing-Engine#1]
Hello, first of all thank you so much for the very light weight rule engine.
Just trying out this project using junit. Found that it is failing for the following rule set(second test). Not sure what could be the issue:
ruleset("Check unit values") {
            require(["isBaseUnit", "isConsumerUnit"])
            rule("Is base unit value matching consumer unit") {
                when { isBaseUnit = isConsumerUnit }
                then { result = 'true' }
                otherwise { result = 'false' }
            }
            test(isBaseUnit: 'true', isConsumerUnit:'true') { result 'true' }
            test(isBaseUnit: 'true', isConsumerUnit:'false') { result 'false' }
        }

When output is traced:
Values are not equal:
(class java.lang.String) true != (class java.lang.String) false
Facts: [result:true, isBaseUnit:false, isConsumerUnit:false]

If you looked at Facts, it is showing `isBaseUnit` is `false` while I passed as `'true'`
Would be glad if you can help to resolve this. Or am using it incorrectly?

**Comment by nmrao** [comment]
The same is passed if Boolean value is passed instead of String as given below:
test(isBaseUnit: true, isConsumerUnit:false) { result 'false' }

**Comment by pmcneil** [comment]
you need an == there :-)

On 26/06/16 12:49, nmrao wrote:

> when { isBaseUnit = isConsumerUnit }

## 

web: http://nerderg.com
Twitter: http://twitter.com/pmcneil
Google+: https://plus.google.com/u/0/communities/110661434396927001866

**Comment by nmrao** [comment]
Thank you so much for swift response. In deed that helped. I do not know, how to close it, but I'll try to close it.
Thank you for your time. Have great day.
